export const StackRegion = {
    ohio: "ohio",
    virginia: "virginia",
    california: "california",
    oregon: "oregon",
    africa: "africa",
    asiaPacificHongKong: "asiaPacificHongKong",
    asiaPacificHyderabad: "asiaPacificHyderabad",
    asiaPacificJakarta: "asiaPacificJakarta",
    asiaPacificMelbourne: "asiaPacificMelbourne",
    asiaPacificMumbai: "asiaPacificMumbai",
    asiaPacificOsaka: "asiaPacificOsaka",
    asiaPacificSeoul: "asiaPacificSeoul",
    asiaPacificSingapore: "asiaPacificSingapore",
    asiaPacificSydney: "asiaPacificSydney",
    asiaPacificTokyo: "asiaPacificTokyo",
    canadaCentral: "canadaCentral",
    europeFrankfort: "europeFrankfort",
    europeIreland: "europeIreland",
    europeLondon: "europeLondon",
    europeMilan: "europeMilan",
    europeParis: "europeParis",
    europeSpain: "europeSpain",
    europeStockholm: "europeStockholm",
    middleEastBahrain: "middleEastBahrain",
    middleEastUae: "middleEastUae",
    southAmericaSaoPaulo: "southAmericaSaoPaulo",
    awsGovCloudEast: "awsGovCloudEast",
    awsGovCloudWest: "awsGovCloudWest",
};

export type StackRegion = (typeof StackRegion)[keyof typeof StackRegion];
